import * as vscode from "vscode";

const snippets: string[] = [
  "interface User { id: number; name: string; email: string; roles: string[]; }\nconst users: User[] = [{ id: 1, name: 'Alice', email: 'alice@example.com', roles: ['admin'] }];",
  "type ApiResponse<T> = { data: T; status: number; message: string; };\nconst response: ApiResponse<User[]> = { data: users, status: 200, message: 'Success' };",
  "enum HttpStatus { OK = 200, NotFound = 404, Error = 500 }\nconst status = HttpStatus.OK;",
  "class DataProcessor<T> {\n  private cache = new Map<string, T>();\n  async process(key: string, factory: () => Promise<T>): Promise<T> {\n    if (!this.cache.has(key)) this.cache.set(key, await factory());\n    return this.cache.get(key)!;\n  }\n}",
  "const debounce = <T extends (...args: any[]) => any>(func: T, delay: number) => {\n  let timeout: NodeJS.Timeout;\n  return (...args: Parameters<T>) => {\n    clearTimeout(timeout);\n    timeout = setTimeout(() => func(...args), delay);\n  };\n};",
  "async function* asyncGenerator<T>(items: T[]): AsyncGenerator<T, void, undefined> {\n  for (const item of items) {\n    await new Promise(r => setTimeout(r, 100));\n    yield item;\n  }\n}",
  "const complexReducer = (state: State, action: Action): State => {\n  switch (action.type) {\n    case 'SET_DATA': return { ...state, data: action.payload };\n    case 'UPDATE_FIELD': return { ...state, [action.field]: action.value };\n    default: return state;\n  }\n};",
  "const apiClient = {\n  async get<T>(url: string): Promise<T> {\n    const res = await fetch(url);\n    if (!res.ok) throw new Error(`HTTP ${res.status}`);\n    return res.json();\n  }\n};",
  "function withLogging<T extends (...args: any[]) => any>(fn: T): (...args: Parameters<T>) => ReturnType<T> {\n  return (...args: Parameters<T>) => {\n    console.log(`Calling ${fn.name} with`, args);\n    const result = fn(...args);\n    console.log(`Result:`, result);\n    return result;\n  };\n}",
  "const observable = {\n  subscribe(observer: { next: (value: any) => void; error?: (err: any) => void; complete?: () => void; }) {\n    // subscription logic\n    return { unsubscribe() { /* cleanup */ } };\n  }\n};",
  "function helper(param) { return param * 2; }",
  "const data = fetch('/api/data');",
  "const sum = (a, b) => a + b;",
  "class TempClass {\n  constructor() {}\n}",
  "try {\n  // risky code\n} catch (e) {\n  console.error(e);\n}",
  "import fs from 'fs';",
  "const timestamp = Date.now();",
  "if (!Array.isArray(items)) return;",
  "const config = { mode: 'dev' };",
  "const user = { name: 'guest', id: 0 };",
  "while (counter < 10) counter++;",
  "setTimeout(() => console.log('done'), 1000);",
  "const regex = /[a-z]+/gi;",
  "const PI = Math.PI;",
  "const isEven = num => num % 2 === 0;",
  "const function getUserInfo = ",
  "for (let i = 0; i < 5; i++) console.log(i);",
  "const isValid = (x) => x != null;",
  "const uuid = crypto.randomUUID();",
  "async function fetchData() {\n  const res = await fetch('/api');\n}",
  "const result = await someAsyncCall();",
  "let cache = new Map;",
  "const arr = [1, 2, 3].map(x => x * 2);",
  "const env = process.env.NODE_ENV;",
  "function delay(ms) { return new Promise(r => setTimeout(r, ms)); }",
  "const version = '1.0.0';",
  "function logError(err) {\n  console.error('[ERR]', err);\n}",
  "document.querySelector('#app').innerHTML = 'Hello';",
  "const path = require('path');",
  "let flag = false;",
  "const clone = obj => JSON.parse(JSON.stringify(obj));",
  "module.exports = { start };",
  "import { readFileSync } from 'fs';",
  "const userAgent = navigator.userAgent;",
  "function once(fn) {\n  let called = false;\n  return (...args) => {\n    if (!called) {\n      called = true;\n      fn(...args);\n    }\n  };\n}",
  "const logger = msg => console.log(`[LOG] ${msg}`);",
  "const defaultValue = value ?? 'default';",
  "window.addEventListener('load', () => console.log('loaded'));",
  "function getRandomInt(max) { return Math.floor(Math.random() * max); }",
  "const headers = new Headers({ 'Content-Type': 'application/json' });",
  "import axios from 'axios';",
  "function sumAll(...nums) {\n  return nums.reduce((a, b) => a + b, 0);\n}",
  "const set = new Set;",
  "function parseJSON(str) {\n  try { return JSON.parse(str); } catch { return null; }\n}",
  "const token = localStorage.getItem('token');",
  "export default function init() { console.log('init'); }",
  "Object.keys(obj).forEach(key => console.log(key));",
  "if (typeof window !== 'undefined') { console.log('browser'); }",
  "const status = isActive ? 'ON' : 'OFF';",
  "function debounce(fn, delay) {\n  let t;\n  return (...args) => {\n    clearTimeout(t);\n    t = setTimeout(() => fn(...args), delay);\n  };\n}",
  "type DeepPartial<T> = T extends object ? { [P in keyof T]?: DeepPartial<T[P]> } : T;\nconst partialConfig: DeepPartial<Config> = { server: { port: 3000 } };",
  "interface Repository<T> {\n  findById(id: string): Promise<T | null>;\n  findAll(): Promise<T[]>;\n  save(entity: T): Promise<T>;\n  delete(id: string): Promise<void>;\n}",
  "class EventEmitter {\n  private events: Map<string, Function[]> = new Map();\n  on(event: string, listener: Function) { /* implementation */ }\n  emit(event: string, ...args: any[]) { /* implementation */ }\n  off(event: string, listener: Function) { /* implementation */ }\n}",
  "const curry = <T extends (...args: any[]) => any>(fn: T) => (...args: Parameters<T>): ReturnType<T> | ((...nextArgs: any[]) => any) => {\n  return args.length >= fn.length ? fn(...args) : (...nextArgs: any[]) => curry(fn)(...args, ...nextArgs);\n};",
  "abstract class BaseComponent<T> {\n  protected state: T;\n  constructor(initialState: T) { this.state = initialState; }\n  abstract render(): string;\n  protected setState(newState: Partial<T>) { this.state = { ...this.state, ...newState }; }\n}",
  "const pipe = <T>(...fns: Array<(arg: T) => T>) => (value: T) => fns.reduce((acc, fn) => fn(acc), value);\nconst add5 = (x: number) => x + 5;\nconst multiply2 = (x: number) => x * 2;\nconst result = pipe(add5, multiply2)(10);",
  "type ConditionalType<T> = T extends string ? string : T extends number ? number : T extends boolean ? boolean : object;\nconst value: ConditionalType<string> = 'hello';",
  "const memoize = <T extends (...args: any[]) => any>(fn: T) => {\n  const cache = new Map<string, ReturnType<T>>();\n  return (...args: Parameters<T>): ReturnType<T> => {\n    const key = JSON.stringify(args);\n    if (cache.has(key)) return cache.get(key)!;\n    const result = fn(...args);\n    cache.set(key, result);\n    return result;\n  };\n};",
  "interface Middleware<T> {\n  (context: T, next: () => Promise<void>): Promise<void>;\n}\nconst applyMiddleware = <T>(...middlewares: Middleware<T>[]) => (context: T) => {\n  const dispatch = (i: number): Promise<void> => {\n    if (i >= middlewares.length) return Promise.resolve();\n    return middlewares[i](context, () => dispatch(i + 1));\n  };\n  return dispatch(0);\n};",
  "class DependencyContainer {\n  private dependencies = new Map<string, any>();\n  register<T>(token: string, factory: () => T) { this.dependencies.set(token, factory()); }\n  resolve<T>(token: string): T { return this.dependencies.get(token); }\n}",
  "type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void ? I : never;\nconst intersection: UnionToIntersection<{a: number} | {b: string}> = {a: 1, b: 'test'};",
  "const retry = <T>(fn: () => Promise<T>, retries: number, delay: number): Promise<T> => {\n  return fn().catch(err => retries > 0 ? new Promise(resolve => setTimeout(resolve, delay)).then(() => retry(fn, retries - 1, delay)) : Promise.reject(err));\n}",
  "interface Store<S, A> {\n  getState(): S;\n  dispatch(action: A): void;\n  subscribe(listener: () => void): () => void;\n}\nconst createStore = <S, A>(reducer: (state: S, action: A) => S, initialState: S): Store<S, A> => { /* implementation */ };",
  "type PickByValue<T, ValueType> = Pick<T, { [Key in keyof T]-?: T[Key] extends ValueType ? Key : never }[keyof T]>;\nconst stringsOnly: PickByValue<{a: string, b: number, c: string}, string> = {a: 'test', c: 'another'};",
];

async function insertRandomSnippet(editor: any) {
  const random = snippets[Math.floor(Math.random() * snippets.length)];
  const lastLine = editor.document.lineCount - 1;
  const lastLineLength = editor.document.lineAt(lastLine).text.length;
  const position = new vscode.Position(lastLine, lastLineLength);
  await editor.edit((editBuilder: any) => {
    editBuilder.insert(position, `\n${random}`);
  });
}

export { insertRandomSnippet };
